services:
  postgres:
    image: postgres
    container_name: trigger-auth-db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trigger-auth
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

  pulsar:
    image: apachepulsar/pulsar
    command: >
      /pulsar/bin/pulsar standalone
    ports:
      - 6650:6650

volumes:
  postgres_data:

networks:
  postgres_network:
