packages:
  - apps/**
  - libs/**

ignoredBuiltDependencies:
  - protobufjs

onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - nx
  - prisma
